apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boardgame
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
      - name:  boardgame
        image: boubakereya22/boardshack:latest
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: boardgame-service
spec:
  selector:
    app: boardgame
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer
